version: '3.9'

services:
  keyword-bot:
    build: .
    container_name: telegram-keyword-bot
    volumes:
      - ./config/global.json:/app/config/global.json
      - ./config/tenants:/app/config/tenants
    restart: always
